<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div align="center">
    <asp:GridView ID="Gridemp" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" OnRowDeleting="Gridemp_RowDeleting">
    <Columns>
        <asp:TemplateField HeaderText="EID">
            <ItemTemplate>
                <asp:Label ID="labeleid" runat="server" Text='<%#Eval("EID") %>'/>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="ENAME">
            <ItemTemplate>
                <%#Eval("ENAME")%>
            </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="SALARY">
            <ItemTemplate>
                <%#Eval("SALARY") %>
            </ItemTemplate>
        </asp:TemplateField>
    </Columns>
     </asp:GridView>
        <br />
        <asp:Label ID="Label1" runat="server" Text=" "></asp:Label>
    </div>
    </form>
</body>
</html>
